#!/bin/sh

OWNCLOUD_PATH=$1
OWNCLOUD_USER=$2
OWNCLOUD_GROUP=$3

chown -R root:$OWNCLOUD_GROUP $OWNCLOUD_PATH/
chown -R $OWNCLOUD_USER:$OWNCLOUD_GROUP $OWNCLOUD_PATH/apps/
chown -R $OWNCLOUD_USER:$OWNCLOUD_GROUP $OWNCLOUD_PATH/config/
chown -R $OWNCLOUD_USER:$OWNCLOUD_GROUP $OWNCLOUD_PATH/data/
chmod -R 750 $OWNCLOUD_PATH/
chmod -R 700 $OWNCLOUD_PATH/data/
chmod 750 $OWNCLOUD_PATH/data/.htaccess
chmod 750 $OWNCLOUD_PATH/data/
chmod -R 700 $OWNCLOUD_PATH/config/
